/**
 * 轻量级拼音映射表
 * 只覆盖菜品名称涉及的中文字，大幅减小体积
 */
const PINYIN_MAP = {
  '番': 'fan', '茄': 'qie', '牛': 'niu', '腩': 'nan',
  '可': 'ke', '乐': 'le', '鸡': 'ji', '翅': 'chi',
  '糖': 'tang', '醋': 'cu', '排': 'pai', '骨': 'gu',
  '宫': 'gong', '保': 'bao', '丁': 'ding',
  '红': 'hong', '烧': 'shao', '肉': 'rou',
  '黑': 'hei', '椒': 'jiao', '柳': 'liu',
  '蒜': 'suan', '香': 'xiang', '葱': 'cong', '爆': 'bao',
  '羊': 'yang', '猪': 'zhu', '蹄': 'ti',
  '酱': 'jiang', '大': 'da', '麻': 'ma', '辣': 'la',
  '水': 'shui', '煮': 'zhu', '鱼': 'yu',
  '牙': 'ya', '签': 'qian',
  '回': 'hui', '锅': 'guo',
  '啤': 'pi', '酒': 'jiu', '鸭': 'ya',
  '盐': 'yan', '皮': 'pi', '虾': 'xia',
  '剁': 'duo', '头': 'tou',
  '叉': 'cha', '干': 'gan', '肥': 'fei', '肠': 'chang',
  '蜜': 'mi', '汁': 'zhi', '狮': 'shi', '子': 'zi',
  '西': 'xi', '柿': 'shi', '炒': 'chao', '蛋': 'dan',
  '地': 'di', '三': 'san', '鲜': 'xian',
  '蓉': 'rong', '兰': 'lan', '花': 'hua',
  '婆': 'po', '豆': 'dou', '腐': 'fu',
  '煸': 'bian', '四': 'si', '季': 'ji',
  '凉': 'liang', '拌': 'ban', '黄': 'huang', '瓜': 'gua',
  '虎': 'hu', '青': 'qing',
  '蚝': 'hao', '油': 'you', '生': 'sheng', '菜': 'cai',
  '空': 'kong', '心': 'xin',
  '酸': 'suan', '土': 'tu', '丝': 'si',
  '松': 'song', '仁': 'ren', '玉': 'yu', '米': 'mi',
  '常': 'chang', '白': 'bai',
  '素': 'su', '苗': 'miao',
  '茄': 'qie', '手': 'shou', '撕': 'si', '包': 'bao',
  '秋': 'qiu', '葵': 'kui',
  '紫': 'zi', '汤': 'tang',
  '玉': 'yu', '鲫': 'ji',
  '南': 'nan', '瓜': 'gua', '浓': 'nong',
  '莲': 'lian', '藕': 'ou',
  '菌': 'jun', '菇': 'gu', '绿': 'lv',
  '罗': 'luo', '宋': 'song',
  '冬': 'dong', '薏': 'yi',
  '饭': 'fan', '葱': 'cong', '拌': 'ban', '面': 'mian',
  '手': 'shou', '工': 'gong', '水': 'shui', '饺': 'jiao',
  '意': 'yi',
  '咖': 'ka', '喱': 'li', '鸡': 'ji',
  '日': 'ri', '式': 'shi', '拉': 'la',
  '烤': 'kao', '面': 'mian', '包': 'bao',
  '扬': 'yang', '州': 'zhou',
  '粉': 'fen', '河': 'he',
  '煎': 'jian',
  '馄': 'hun', '饨': 'tun',
  '夹': 'jia', '馍': 'mo',
  '炸': 'zha', '酱': 'jiang',
  '泡': 'pao', '菜': 'cai',
  '热': 're', '干': 'gan',
  '煲': 'bao', '仔': 'zai',
  '芒': 'mang', '果': 'guo', '布': 'bu', '丁': 'ding',
  '双': 'shuang', '皮': 'pi', '奶': 'nai',
  '蛋': 'dan', '挞': 'ta',
  '红': 'hong', '豆': 'dou', '沙': 'sha',
  '糍': 'ci', '粑': 'ba',
  '草': 'cao', '莓': 'mei', '酸': 'suan', '奶': 'nai',
  '糯': 'nuo',
  '焦': 'jiao', '糖': 'tang',
  '雪': 'xue', '媚': 'mei', '娘': 'niang',
  '芋': 'yu', '圆': 'yuan', '仙': 'xian', '草': 'cao',
  '提': 'ti', '拉': 'la', '米': 'mi', '苏': 'su',
  '水': 'shui', '果': 'guo', '蛋': 'dan', '糕': 'gao',
  '冰': 'bing', '粉': 'fen',
  '烤': 'kao', '红': 'hong', '薯': 'shu',
  '糖': 'tang', '葫': 'hu', '芦': 'lu',
  '鲜': 'xian', '榨': 'zha', '橙': 'cheng', '汁': 'zhi',
  '柠': 'ning', '檬': 'meng', '蜂': 'feng', '蜜': 'mi',
  '巧': 'qiao', '克': 'ke', '力': 'li',
  '抹': 'mo', '茶': 'cha', '拿': 'na', '铁': 'tie',
  '美': 'mei', '式': 'shi',
  '西': 'xi', '瓜': 'gua',
  '椰': 'ye',
  '昔': 'xi',
  '梅': 'mei',
  '百': 'bai', '香': 'xiang', '绿': 'lv',
  '桂': 'gui', '花': 'hua', '酒': 'jiu', '酿': 'niang',
  '面': 'mian', '牛': 'niu',
  '里': 'li', '脊': 'ji',
  '猪': 'zhu', '肉': 'rou',
  '油': 'you', '豆': 'dou', '腐': 'fu',
  '块': 'kuai',
  '片': 'pian',
  '丝': 'si',
  '条': 'tiao',
  '块': 'kuai',
  '小': 'xiao',
  '排': 'pai', '骨': 'gu',
  '老': 'lao',
  '新': 'xin',
  '鲜': 'xian',
  '清': 'qing',
  '蒸': 'zheng',
  '汁': 'zhi',
  '浓': 'nong',
  '甜': 'tian',
  '咸': 'xian',
  '脆': 'cui',
  '嫩': 'nen',
  '滑': 'hua',
  '爽': 'shuang',
  '绵': 'mian',
  '软': 'ruan',
  '糯': 'nuo',
  '酥': 'su',
  '焦': 'jiao',
}

function getPinyin(str) {
  let result = ''
  for (const char of str) {
    result += PINYIN_MAP[char] || char
  }
  return result
}

function getInitials(str) {
  let result = ''
  for (const char of str) {
    const py = PINYIN_MAP[char]
    result += py ? py[0] : char
  }
  return result
}
